### ISSUE TITLE
you do not see the icons but the code

### ISSUE THREAD

**Issue by riccardo65** [james-fry/home-assistant-mdi#4]
good morning unfortunately you no longer see the icons but the code that makes this addon
how can i solve thanks
![problema mdi icon index](https://user-images.githubusercontent.com/63116389/135002702-3ea3812e-2a97-4685-b6f8-1c849e650680.JPG)

**Comment by joe-0310** [comment]
Exactly the same problem for me!

**Comment by james-fry** [comment]
Please can you try this link:
https://rawgit.com/james-fry/home-assistant-mdi/master/home-assistant-mdi.html

Works for me.
I will update the readme if also working for you?

**Comment by joe-0310** [comment]
Thanks for the quick reply. Works great now!

**Comment by james-fry** [comment]
Thanks for confirming, Looks like the github CDN link in the readme was no longer valid. I updated the readme to the persistent link you have confirmed.
