### ISSUE TITLE
rawgit.com no longer works

### ISSUE THREAD

**Issue by wvoigt** [james-fry/home-assistant-mdi#6]
The rawgit installation no longer works.  From rawgit.com website: 
`RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.  GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.`

I have found an alternative way to serve the html file directly from github:
**"https://raw.githack.com/james-fry/home-assistant-mdi/master/home-assistant-mdi.html"**

The readme documentation should be updated.

**Comment by james-fry** [comment]
Thanks I will update the readme

**Comment by james-fry** [comment]
Updated
