### ISSUE TITLE
showing the html code instead of the visual interface

### ISSUE THREAD

**Issue by nbexiga** [james-fry/home-assistant-mdi#7]
Hello.
I don't know if it's an issue , but since 27 nov i noticed that the main page in HA does not show the content as it was supposed and i was working till then.
but it is showing the HTML code for the page.
even if i browse to the url https://cdn.jsdelivr.net/gh/james-fry/home-assistant-mdi@efd95d7a/home-assistant-mdi.html it shows the content and not the visual content itself.

can you please help if this is known or an issue from my side?
thank you.
Regard
![fromha](https://user-images.githubusercontent.com/34128424/143930483-154e2aa5-c544-4422-89a8-52ad2f301bfa.png)
![frombrowser](https://user-images.githubusercontent.com/34128424/143930487-2f28d5a4-b580-40ad-8366-458fdc1db861.png)
s

**Comment by johnnysmithy852456** [comment]
Me too

**Comment by james-fry** [comment]
Hi Guys,

PLease check the updated readme and closed issues.
The URL for live version is now: 
https://raw.githack.com/james-fry/home-assistant-mdi/master/home-assistant-mdi.html
